[package]
name = "pws"
version = "0.1.0"
authors = ["pjotr"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.105.0"
